name: Periodic health check

on:
  push:
    branches:
      - main
  #schedule:
    #- cron: '0 * * * *'

jobs:
  periodic_health_check_cron:
    runs-on: ubuntu-22.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: https://phonebook-jgkw.onrender.com/
        max-attempts: 4
        retry-delay: 5s
    - name: Deployment success actor
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() && github.event_name != 'schedule' }}
      with:
        status: Success
        description: URL https://phonebook-jgkw.onrender.com/ checked by ${{ github.actor }}
        content: Periodic health check passed
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Deployment success cron
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() && github.event_name == 'schedule' }}
      with:
        status: Success
        description: URL https://phonebook-jgkw.onrender.com/ checked by cron
        content: Periodic health check passed
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Deployment failure actor
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() && github.event_name != 'schedule' }}
      with:
        status: Failure
        description: URL https://phonebook-jgkw.onrender.com/ checked by ${{ github.actor }}
        content: Periodic health check failed
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Deployment failure cron
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() && github.event_name == 'schedule' }}
      with:
        status: Failure 
        description: URL https://phonebook-jgkw.onrender.com/ checked by cron
        content: Periodic health check failed
        webhook: ${{ secrets.DISCORD_WEBHOOK }}