name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '22.16.0'
      - name: npm run install
        run: npm run install  
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:ui
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          command: npm run test:e2e
          start: npm run start & npm run preview:ui && fg
          wait-on: http://localhost:4173
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deployment success actor
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() && github.event_name != 'schedule' }}
        with:
          status: Success
          description: to https://phonebook-jgkw.onrender.com/ by ${{ github.actor }}
          content: A new version of Phonebook deployed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment success cron
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() && github.event_name == 'schedule' }}
        with:
          status: Success
          description: to https://phonebook-jgkw.onrender.com/ by cron
          content: A new version of Phonebook deployed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment failure actor
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() && github.event_name != 'schedule' }}
        with:
          status: Failure
          description: commit ${{ github.event.head_commit.url }} by ${{ github.actor }} broke the build :(
          content: Build failed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment failure cron
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() && github.event_name == 'schedule' }}
        with:
          status: Failure 
          description: commit ${{ github.event.head_commit.url }} by cron broke the build :(
          content: Build failed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch